// Sprites.jsx — Pixel art sprites via CSS box-shadow.
// Convertido do amazonia-standalone para ES module.

export function PixelSprite({ matrix, palette, px = 4, style = {}, className = '' }) {
  const rows = matrix.trim().split('\n').map(r => r.trim());
  const h = rows.length;
  const w = Math.max(...rows.map(r => r.length));
  const shadows = [];
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const ch = rows[y][x];
      if (!ch || ch === '.') continue;
      const color = palette[ch];
      if (!color) continue;
      shadows.push(`${x * px}px ${y * px}px 0 ${color}`);
    }
  }
  return (
    <div className={className} style={{ position: 'relative', width: w * px, height: h * px, ...style }}>
      <div style={{ position: 'absolute', width: px, height: px, boxShadow: shadows.join(','), top: 0, left: 0 }} />
    </div>
  );
}

// --- Animais ---

const antPal = { k: '#1a0e06', K: '#2a1a0e', r: '#6b2810', b: '#4a1808' };
const antMatrix = `
..............
.k..k.........
..k.k.........
...kkkKKKKK...
..KKKKkkkkkKK.
.KKKkkkkkkkkK.
.KkkkkkkkkkK..
.Kk.k.k..k.k..
..k.k.k..k.k..
..............`;
export function SpriteAnt({ size = 4, style }) {
  return <PixelSprite matrix={antMatrix} palette={antPal} px={size} style={style} />;
}

const sprPal = { b: '#c9915a', B: '#8b5a32', w: '#f5e6c8', k: '#1a0e06', d: '#4a2208', h: '#6b3418' };
const sprMatrix = `
....................
...........hh.......
..........hkh.......
..........hkh.......
..........bbb.......
.......BBBbbbbB.....
......BbbbbbbbbB....
.....Bbbwwwwwbbb....
....BbbwwwwwwwbbB...
...BbbwwwwwwwwwbB...
...BbbwwwwwwwwwbB...
...BBbbwwwwwbbbBB...
....B.B.....B.B.....
....B.B.....B.B.....
....k.k.....k.k.....
....................`;
export function SpriteSpringbok({ size = 4, style }) {
  return <PixelSprite matrix={sprMatrix} palette={sprPal} px={size} style={style} />;
}

const oncaPal = { o: '#d89a40', O: '#b87020', k: '#2a1a0e', w: '#f5e6c8', p: '#1a0e06', r: '#6b3410' };
const oncaMatrix = `
......................
....OOOO..............
...OowoOO.............
..OopopooOOOOOO.......
..OoookoooooooOO......
..OoooookooookooO.....
...OokoooookoooO......
....OOoookoooooO......
.....OkOOOOOOOkO......
.....O.O....O.O.......
.....O.O....O.O.......
.....p.p....p.p.......
......................
......................`;
export function SpriteOnca({ size = 4, style }) {
  return <PixelSprite matrix={oncaMatrix} palette={oncaPal} px={size} style={style} />;
}

const tucPal = { k: '#1a0e06', K: '#0a0604', o: '#ea580c', y: '#fbbf24', w: '#f5e6c8', b: '#d97706' };
const tucMatrix = `
............
.....kkk....
....kKKKk...
...kKKyyoo..
..kKKKyoooo.
..kKKKKooob.
..kKKKKKkb..
..kKKKKKk...
...kKKKk....
....kKk.....
.....k......
.....k......
....k.k.....
............`;
export function SpriteTucano({ size = 4, style }) {
  return <PixelSprite matrix={tucMatrix} palette={tucPal} px={size} style={style} />;
}

const araraPal = { b: '#2040a0', B: '#102060', y: '#fbbf24', k: '#1a0e06' };
const araraMatrix = `
............
.....bbb....
....bBBBb...
...bBByykk..
..bBBByyykk.
..bBBBBBkk..
..bBBBBBk...
..bBBBBBb...
...bBBBb....
....bBb.....
.....b......
.....b......
....k.k.....
............`;
export function SpriteArara({ size = 4, style }) {
  return <PixelSprite matrix={araraMatrix} palette={araraPal} px={size} style={style} />;
}

// --- Vegetação ---

const treePal = { t: '#5a3418', T: '#3a2008', o: '#ea580c', O: '#b8431f', y: '#fbbf24', r: '#a0321e', g: '#84a05c' };
const treeAutumnMatrix = `
......ooo.........
....ooOOOOoo......
...oOOyyOOOo......
..oOOyyOyyOOo.....
..oOOyOOyyOOOo....
.oOrrOOyyOOOOOo...
.oOOOOyyyrrOOOo...
.oOOrrOOOOOOOOo...
..oOOOOOOrrOOo....
...oOOOOOOOOo.....
....ooOOOOoo......
........tt........
.......tTt........
.......tTt........
.......tTt........`;
export function SpriteTreeAutumn({ size = 4, style }) {
  return <PixelSprite matrix={treeAutumnMatrix} palette={treePal} px={size} style={style} />;
}

const pinePal = { d: '#3d4a28', D: '#2a3518', l: '#5c7040', t: '#4a2208' };
const pineMatrix = `
.......l.......
......ldl......
.....lddDl.....
....lddDDdl....
...lddDDDDdl...
..lddDDDDDDdl..
...lddDDDDdl...
..lddDDDDDDdl..
.lddDDDDDDDDdl.
..lddDDDDDDdl..
.......t.......
.......t.......
.......t.......`;
export function SpritePine({ size = 4, style }) {
  return <PixelSprite matrix={pineMatrix} palette={pinePal} px={size} style={style} />;
}

const bushPal = { g: '#84a05c', G: '#5c7040', d: '#3d4a28' };
const bushMatrix = `
................
...gggg..gggg...
..gGGGGggGGGGg..
.gGGddGGGGddGGg.
gGdddGGGGGGdddGg
gGGGGGGddGGGGGGg
.gGGGGddddGGGGg.
..gGGddddddGGg..
...gggddddggg...
....ggddddgg....`;
export function SpriteBush({ size = 4, style }) {
  return <PixelSprite matrix={bushMatrix} palette={bushPal} px={size} style={style} />;
}

const cactusPal = { c: '#5c7040', C: '#3d4a28', y: '#fbbf24', d: '#2a3518' };
const cactusMatrix = `
.............
...cc........
..cCCc.cc....
..cCCc.cCc...
..cCCccCCc...
..cCCCCCCc...
..cCCCCCCc...
..cCCyCCCc...
..cCCCCCCc...
..cCCCCCCc...
...cCCCCc....
...cCCCCc....
...cddddc....`;
export function SpriteCactus({ size = 4, style }) {
  return <PixelSprite matrix={cactusMatrix} palette={cactusPal} px={size} style={style} />;
}

const rockPal = { r: '#6b5033', R: '#4a3420', l: '#8b6d4a', d: '#2a1a0e' };
const rockMatrix = `
................
....lrrrl.......
...lRRrRRRl.....
..lRRRrRRRRl....
.lRRRrRRRRRRl...
.lRdRRRRRRddl...
..lRRRRdRRRl....
...ldRRRRRdl....
....lddddll.....`;
export function SpriteRock({ size = 4, style }) {
  return <PixelSprite matrix={rockMatrix} palette={rockPal} px={size} style={style} />;
}

const grassPal = { g: '#84a05c', G: '#5c7040' };
const grassMatrix = `
.g.g.g.g.
gGgGgGgGg
gGGGGGGGg
.GGGGGGG.`;
export function SpriteGrass({ size = 4, style }) {
  return <PixelSprite matrix={grassMatrix} palette={grassPal} px={size} style={style} />;
}

const leafPal = { o: '#ea580c', y: '#fbbf24', r: '#a0321e' };
const leafMatrix = `
.oo.
oooy
yyor
.rr.`;
export function SpriteLeaf({ size = 3, style }) {
  return <PixelSprite matrix={leafMatrix} palette={leafPal} px={size} style={style} />;
}

const logPal = { t: '#5a3418', T: '#3a2008', l: '#8b5a32', r: '#4a2208' };
const logMatrix = `
..................
.tTTTTTTTTTTTTTTt.
tTllllllllllllllTt
tTlrrlrrlrrlrrrllTt
tTllllllllllllllTt
.tTTTTTTTTTTTTTTt.`;
export function SpriteLog({ size = 4, style }) {
  return <PixelSprite matrix={logMatrix} palette={logPal} px={size} style={style} />;
}

const sunPal = { y: '#fbbf24', Y: '#fef08a', o: '#ea580c' };
const sunMatrix = `
...yyyy...
..yYYYYy..
.yYYYYYYy.
yYYYYYYYYy
yYYYYyyyYy
yYYyyyyyYy
yYyyyyyyyo
.yyyyyyyo.
..yyyyyo..
...yoyo...`;
export function SpriteSun({ size = 4, style }) {
  return <PixelSprite matrix={sunMatrix} palette={sunPal} px={size} style={style} />;
}

const cloudPal = { w: '#fef4a8', W: '#f5e6c8', s: '#e8d4a8' };
const cloudMatrix = `
...wwww......
..wWWWWww....
.wWWWWWWWw...
wWWWWWWWWWw..
.wsswwsswwss.
..sssssssss..`;
export function SpriteCloud({ size = 4, style }) {
  return <PixelSprite matrix={cloudMatrix} palette={cloudPal} px={size} style={style} />;
}

const firePal = { o: '#ea580c', y: '#fbbf24', r: '#a0321e', t: '#5a3418', T: '#3a2008', k: '#1a0e06' };
const fireMatrix = `
.....y......
....yyy.....
...yooy.....
..ooooyo....
..ryooor....
..roooor....
..rroorr....
.tTTkkTTt...
.ttTkkTtt...`;
export function SpriteFire({ size = 4, style }) {
  return <PixelSprite matrix={fireMatrix} palette={firePal} px={size} style={style} />;
}

const signPal = { w: '#8b5a32', W: '#a06a3e', d: '#4a2208', D: '#2a1a0e' };
const signMatrix = `
...DDDDDDDDDDDDD...
..DwWWWWWWWWWWWwD..
..DwWWWWWWWWWWWwD..
..DwWWWWWWWWWWWwD..
..DwWWWWWWWWWWWwD..
..DDDDDDDDDDDDDDD..
.......DDD.........
.......DDD.........
.......DDD.........
......DDDDD........`;
export function SpriteSign({ size = 4, style }) {
  return <PixelSprite matrix={signMatrix} palette={signPal} px={size} style={style} />;
}
